[project]
name = "nhl-score-processing-for-prelim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "pandas>=2.3.0",
    "streamlit>=1.45.1",
]
